fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

index:
    path: /
    controller: App\Controller\PageController::index

gallery:
    path: /gallery
    controller: App\Controller\PageController::gallery

book_create_page:
    path: /gallery/book/create
    controller: App\Controller\PageController::bookCreate
    
book_create_handler:
    path: /gallery/book/handler
    controller: App\Controller\BookController::bookHandler
    
book_edit_handler:
    path: /gallery/book/handler
    controller: App\Controller\BookController::bookHandler
    
api_book_create:
    path: /api/v1/books/add
    controller: App\Controller\BookController::addBook

api_book_edit:
    path: /api/v1/books/{id}/edit
    controller: App\Controller\BookController::editBook
    requirements:
        id: '\d+'

api_books_get:
    path: /api/v1/books
    controller: App\Controller\BookController::getBookS
