fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_login:
    path: /login
    controller: App\Controller\UserController:loginAction

index:
    path: /
    controller: App\Controller\PageController::index

gallery:
    path: /gallery/
    controller: App\Controller\PageController::gallery

book_create_page:
    path: /gallery/book/create
    controller: App\Controller\PageController::bookCreate
    
book_edit_page:
    path: /gallery/book/{id}/
    controller: App\Controller\PageController::bookEdit
    requirements:
        id: '\d+'
    
book_create_handler:
    path: /gallery/book/create/handler
    controller: App\Controller\BookController::bookHandler
    methods: [POST]
    
book_edit_handler:
    path: /gallery/book/{id}/edit
    controller: App\Controller\BookController::bookHandler
    methods: [POST]
    
book_delete_handler:
    path: /gallery/book/{id}/delete
    controller: App\Controller\BookController::bookDelete
    methods: [GET]
    
api:
    resource: "routes_api.yaml"
    prefix:   /api/v1
